### ISSUE TITLE
Running on web

### ISSUE THREAD

**Issue by karims** [willi-menapace/PlayableVideoGeneration#4]
I'm trying to run pre-trained models on remote server and I want to visualize interaction like in the demo website. 

Is it possible that you can point out the source code of the demo website?

Also, is it possible to run the pre-trained models on jupyter and see the video generation?

**Comment by willi-menapace** [comment]
Dear Karims, you can find the source code for the demo website at this address https://github.com/willi-menapace/playable-video-generation-website.

Running the pretrained models on jupyter is possible, but this functionality has not been implemented. If you'd like to implement it I suggest starting from the code in the play.py file which can be executed on your machine to interact with the models and save resulting videos in a variety of formats.

**Comment by karims** [comment]
Thanks so much willi. :)
