### ISSUE TITLE
Error when locating font

### ISSUE THREAD

**Issue by RyannDaGreat** [willi-menapace/PlayableVideoGeneration#7]
Line 32 of PlayableVideoGeneration/utils/save_video_ffmpeg.py should be 
`font = ImageFont.truetype("utils/fonts/Roboto-Regular.ttf", pointsize)` 
and not `font = ImageFont.truetype("fonts/Roboto-Regular.ttf", pointsize)`. 
This error makes `python play.py --config configs/02_breakout.yaml` fail

**Comment by willi-menapace** [comment]
Dear Ryan,
thanks for reporting the problem. I will update the file as you suggest

Best
